---
# tasks file for role_skeleton
  - name: Donwload splunk package
    get_url:
      url: "{{ download_url }}"
      dest: "{{ download_location }}"
  - name: Install splunk deb package
    apt:
      update_cache: yes
      deb: "{{ package_location }}"
  - name: Enabled boot start
    service:
      name: splunk
      pattern: /opt/splunk/bin/splunk
      enabled: yes
      

    