---
- name: create springpet-clinic linux service
  hosts: appserver
  become: yes
  tasks:
    - name: Update and Install openjdk-11
      apt:
        name: openjdk-11-jdk
        update_cache : yes
        state: present
    - name: Create directory springpetclinic
      ansible.builtin.file:
        path: /usr/share/springpetclinic
        state: directory
    - name: Download springpet-clinic jar 
      get_url:
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar